### PR TITLE
Favorites detail

### PR DESCRIPTION
**Pull request by geeegrace02**
In favorites-detail branch, we have done.

- Implement characters, comics and series details section.
- Implement favorite feature.
- Implement favorite page.
- Implement about page.
- Update navigation bar.

### CODE REVIEW

**Review by mjrchy — DISMISSED** [review]
Could you edit the error message to be more understandable, please?

**Review by Sankrub — APPROVED** [review]
Nicely every feature implement and update in this working fine after checking. And this ready to Merge. Nice work my team!!

**Review by mjrchy — APPROVED** [review]
Thanks for edit the error message! Approved to merge this branch to main!

**Review by oatwarat — APPROVED** [review]
great feature!

**Comment by geeegrace02** [comment]
Alright , It's time to merge!!

**Pull request merged**
