### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by Sankrub**
In authentication branch we have done.
1. User authentication
2. Implement and customize login and signup page.
3. Unittest for user authentication
4. Implement login with social account(Google mail).

### CODE REVIEW

**Comment by mjrchy** [comment]
The navigation bar looks great, and user authentication is highly functional. Excellent work! I approve the merge.

**Comment by geeegrace02** [comment]
The overall codebase is cleaner, more effective and more usable. This is very beneficial to our project!!!

**Comment by oatwarat** [comment]
The authentication feature is excellently implemented,

**Review by oatwarat — COMMENTED** [review]
The authentication feature is excellently implemented,

**Review by mjrchy — COMMENTED** [review]
The navigation bar looks great, and user authentication is highly functional. Excellent work! I approve the merge.

**Pull request merged**
