### PR TITLE
Reset pass

### PR DESCRIPTION
**Pull request by Sankrub**
Implement reset password for user. Reset password sent to the email user registered. Then user can create new password by clicking the link they receive in the email.

### CODE REVIEW

**Review by oatwarat — APPROVED** [review]
great feature brother!

**Review by geeegrace02 — APPROVED** [review]
Well done!! cause it's a functionally feature!!

**Review by mjrchy — APPROVED** [review]
Everything is great and functionally. Approved!

**Comment by Sankrub** [comment]
Okay thanks let merge!

**Pull request merged**
