### PR TITLE
Deploy app

### PR DESCRIPTION
**Pull request by mjrchy**
Files for deploy application
- Procfile
- Edit setting
- runtime.txt
- requirement.txt
- Edit description data types in models

### CODE REVIEW

**Review by Sankrub — APPROVED** [review]
All the files is needed for deploy. Nice

**Review by oatwarat — APPROVED** [review]
very well deployment!

**Comment by geeegrace02** [comment]
Overall files are complete and correct!! Lets deploy!!

**Review by geeegrace02 — APPROVED** [review]
Overall files are complete and correct!! Lets deploy!!

**Pull request merged**
