### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by mjrchy**
In home-page branch, we have done.
- Implement homepage.
- Implement all-characters, all-comics and all-series pages.
- Implement search feature.
- Update navigation bar.

### CODE REVIEW

**Review by Sankrub — COMMENTED** [review]
1. Fix some image url 404

**Comment by geeegrace02** [comment]
NICE!!! All minor and major issues are all fixed!!

**Review by oatwarat — COMMENTED** [review]
make an x mark on search button so user can clear their search

**Comment by geeegrace02** [comment]
Add a default image for the URL that contains the 404 response code, and use every 7 cards for each slide of the card slider.

**Comment by mjrchy** [comment]
I have already added all the suggestions. Please take a look!

**Comment by geeegrace02** [comment]
I suggest you to change into `refresh icon` instead of the `X mark icon` for clear search button.

**Comment by mjrchy** [comment]
I have already change clear search button. Thanks for your suggestions!

**Review by oatwarat — APPROVED** [review]
great work jiratchaya!

**Comment by mjrchy** [comment]
Thanks!

**Pull request merged**
